//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsr_forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sports
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Img { get; set; }
    }
}
