//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsr_forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int PhotoId { get; set; }
        public int ZodiakId { get; set; }
        public int TemperamentId { get; set; }
        public int CharacterId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Zodiak Zodiak { get; set; }
        public virtual Temperament Temperament { get; set; }
        public virtual Character Character { get; set; }
    }
}
